# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RAble
                                 A QGIS plugin
 //TODO
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-07-18
        copyright            : (C) 2023 by WIZIPISI
        email                : //TODO
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import sys
from qgis.core import *


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RAble class from file RAble.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    installDependencies(iface)
    from .r_able import RAble
    return RAble(iface)


def installDependencies(iface):
    dependencies_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'dependencies')
    try:
        import validators
    except ImportError:
        path = os.path.join(dependencies_dir, 'validators-0.22.0-py3-none-any.whl')
        sys.path.append(path)
        import validators
